/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit5gradle;


import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        assertTrue(classUnderTest.someLibraryMethod());
    }
}
